-- Inserting a Gift Card
INSERT INTO BLC_CREDIT_ACCOUNT (CREDIT_ACCOUNT_ID, BALANCE, CURRENCY_CODE, VERSION_NUM) VALUES (1002, 15.00, null, 1);
INSERT INTO BLC_GIFT_CARD_ACCOUNT (CREDIT_ACCOUNT_ID, GIFT_CARD_NUMBER, RECIPIENT_EMAIL_ADDRESS ) VALUES (1002, '11','jocanas@broadleafcommerce.com');

INSERT INTO BLC_CREDIT_ACCOUNT (CREDIT_ACCOUNT_ID, BALANCE, CURRENCY_CODE, VERSION_NUM) VALUES (1001, 20.00, null, 1);
INSERT INTO BLC_GIFT_CARD_ACCOUNT (CREDIT_ACCOUNT_ID, GIFT_CARD_NUMBER, RECIPIENT_EMAIL_ADDRESS ) VALUES (1001, '21','jocanas@broadleafcommerce.com');
