-- Inserting a Gift Card
INSERT INTO BLC_CREDIT_ACCOUNT (CREDIT_ACCOUNT_ID, BALANCE, VERSION_NUM) VALUES (1, 10.00, 1);
INSERT INTO BLC_GIFT_CARD_ACCOUNT (CREDIT_ACCOUNT_ID, GIFT_CARD_NUMBER, RECIPIENT_EMAIL_ADDRESS ) VALUES (1, '21','jocanas@broadleafcommerce.com');